# Generated by Django 6.0.6 on 2026-07-10 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="profile_pic",
            field=models.ImageField(
                blank=True, default="profile_default_pic.jpg", upload_to="profile_pic"
            ),
        ),
    ]
