# Generated by Django 6.0.6 on 2026-07-10 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="cover_picture",
            field=models.ImageField(
                blank=True, default="cover_default_pic.jpg", upload_to="cover_pic"
            ),
        ),
    ]
